// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejcdtdwqiqltnlvpbkaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqY2R0ZHdxaXFsdG5sdnBia2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NTU3MDMsImV4cCI6MjA1NzQzMTcwM30.54GWESgzlAVxaAdzTmpC_08DKR5Wg0iSop0vIoSL7Xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);